name: coverage

on: [ pull_request ]

jobs:
  coverage:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Openjdk
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21

      - name: Show java version
        run: |
          java -Xmx32m -version

      - name: Show javac version
        run: |
          javac -J-Xmx32m -version

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          lein: 2.12.0

      - name: Show leiningen version
        run: |
          lein version

      - name: Run cloverage
        run: |
          lein cloverage --codecov

      - name: Push cloverage result
        run: |
          bash <(curl -s https://codecov.io./bash) -f target/coverage/codecov.json
