name: test

on: [ push ]

jobs:
  test:
    strategy:
      matrix:
        os:
          - Ubuntu-22.04
        openjdk:
          - 8
          - 11
          - 17
          - 21
          - 25
        clojure:
          - 1.8
          - 1.9
          - 1.10
          - 1.11
          - 1.12
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Openjdk
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: ${{ matrix.openjdk }}

      - name: Show java version
        run: |
          java -Xmx32m -version

      - name: Show javac version
        run: |
          javac -J-Xmx32m -version

      - name: Install leiningen
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 2.11.2

      - name: Show leiningen version
        run: |
          lein version

      - name: Run test
        run: |
          lein with-profile dev,${{ matrix.clojure }} test

      - name: Run cljs test
        run: |
          lein with-profile dev,${{ matrix.clojure }} cljsbuild test
